name: Business Consulting
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#344b75'
    - '#040406'
    - '#ffffff'
    - '#7b6b76'
    - '#7696bc'
  brandStrength: 0.8125
  lightness: 0.000514522660523653
  saturation: 0.29453703365288675
  rhythmicContrast: 0.8581488409545273
purpose: []
